---

# Tasks file for kibana

- name: 'Load the OS specific varibles'
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"
  tags:
    - 'install'
    - 'kibana'


- include: 'install_debian.yml'
  when: "{{ ansible_os_family == 'Debian' }}"
  tags:
    - 'install'
    - 'kibana'


- include: 'configure.yml'
  tags:
    - 'configure'
    - 'kibana'
