---

# Tasks file for kibana

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::kibana'
    - 'role::kibana::init'
    - 'role::kibana::install'
    - 'role::kibana::configure'


- name: 'INSTALL | Include installation tasks for OS family'
  become: True
  include: "{{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yml"
  tags:
    - 'role::kibana'
    - 'role::kibana::install'


- name: 'CONFIG | Include configuration tasks'
  include: "{{ role_path }}/tasks/configure.yml"
  tags:
    - 'role::kibana'
    - 'role::kibana::configure'
