---

# Tasks file for kibana

- name: 'INIT | Manage variables to use for our target'
  include: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::kibana'
    - 'role::kibana::init'


- name: 'Load the OS specific varibles'
  include_vars: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"
  tags:
    - 'install'
    - 'kibana'


- include: 'install_debian.yml'
  when: "{{ ansible_os_family == 'Debian' }}"
  tags:
    - 'install'
    - 'kibana'


- include: 'configure.yml'
  tags:
    - 'configure'
    - 'kibana'
