---

# Handlers main file for kibana role

- name: 'HANDLER | Restart kibana'
  become: True
  service:
    name: "{{ kibana_service_name }}"
    state: 'restarted'
  when: "kibana_service_state != 'stopped'"
  tags:
    - 'role::kibana'
    - 'role::kibana::install'
    - 'role::kibana::configure'
